cc_test(
    name='random_graph_test',
    srcs=[
        'random_graph_test.cc',
        'core.h',
    ],
    copts=[
        '-std=c++14',
        '-O3',
        '-march=native',
        '-Wall',
        '-fno-rtti',
        '-fno-exceptions',
    ],
    linkopts=[
        '-lgtest_main',
        '-lgtest',
        '-pthread',
    ],
)

cc_test(
    name='dominator_tree_test',
    srcs=[
        'dominator_tree_test.cc',
        'core.h',
    ],
    copts=[
        '-std=c++14',
        '-O3',
        '-march=native',
        '-Wall',
        '-fno-rtti',
        '-fno-exceptions',
    ],
    linkopts=[
        '-lgtest_main',
        '-lgtest',
        '-pthread',
    ],
)

cc_test(
    name='scc_test',
    srcs=[
        'scc_test.cc',
        'core.h',
    ],
    copts=[
        '-std=c++14',
        '-O3',
        '-march=native',
        '-Wall',
        '-fno-rtti',
        '-fno-exceptions',
    ],
    linkopts=[
        '-lgtest_main',
        '-lgtest',
        '-pthread',
    ],
)

cc_test(
    name='lca_test',
    srcs=[
        'lca_test.cc',
        'core.h',
    ],
    copts=[
        '-std=c++14',
        '-O3',
        '-march=native',
        '-Wall',
        '-fno-rtti',
        '-fno-exceptions',
    ],
    linkopts=[
        '-lgtest_main',
        '-lgtest',
        '-pthread',
    ],
)

cc_test(
    name='max_flow_test',
    srcs=[
        'max_flow_test.cc',
        'core.h',
    ],
    copts=[
        '-std=c++14',
        '-O3',
        '-march=native',
        '-Wall',
        '-fno-rtti',
        '-fno-exceptions',
    ],
    linkopts=[
        '-lgtest_main',
        '-lgtest',
        '-pthread',
    ],
)

cc_test(
    name='sched_test',
    srcs=[
        'sched_test.cc',
        'core.h',
    ],
    copts=[
        '-std=c++14',
        '-O3',
        '-march=native',
        '-Wall',
        '-fno-rtti',
        '-fno-exceptions',
    ],
    linkopts=[
        '-lgtest_main',
        '-lgtest',
        '-pthread',
    ],
)
