name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test_cc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install gtest
      run: sudo apt install -y libgtest-dev
    - name: test
      run: bazel test :all

  test_rs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install rust
      run: sudo apt install -y cargo
    - name: test
      run: cd rust && cargo t
    - name: bench
      run: cd rust && cargo bench
