name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test_cc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install gtest
      run: sudo apt install -y libgtest-dev
    - name: Test
      run: bazel test :all
